name: Salesforce validation

on:
  pull_request:
    branches: ["dev", "homolog", "main"]
  push: 
    branches: ["dev", "homolog", "main"]
    
jobs:

  validationDev:
    if: github.base_ref == 'dev'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - name: Validating on Development environment
    - run: echo  Estou rodando na dev
    - run: sfdx version
    
  validationHomolog:
    if: github.base_ref == 'homolog'
    environment: Homologation
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - name: Validating on Homologation environment
    - run: echo  Estou rodando na homolog
    - run: sfdx version
    
  validationMain:
    if: github.base_ref == 'main'
    environment: Production
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - name: Validating on Production environment
    - run: echo  Estou rodando na main
    - run: sfdx version
    
  deploymentDev:
    if: github.event_name	== 'push'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - name: Deploying on Development environment
    - run: echo "Estou implantando na dev"
    
    
    
    
