name: Salesforce CI/CD pipeline

on:
  pull_request:
    branches: ["dev", "homolog", "main"]
  push: 
    branches: ["dev", "homolog", "main"]
  
jobs:

  validationDev:
    if: github.base_ref == 'dev'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full

    steps:
    - run: echo "Estou rodando na dev"
    - run: sfdx version
    - run: echo "${{ vars.ENVIROMENT_NAME }}"
    
  validationHomolog:
    if: github.base_ref == 'homolog'
    environment: Homologation
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full

    steps:
    - run: echo  Estou rodando na homolog
    - run: sfdx version
    
  validationMain:
    if: github.base_ref == 'main'
    environment: Production
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full

    steps:
    - run: echo  Estou rodando na main
    - run: sfdx version
    
  deploymentDev:
    if: github.ref_name == 'dev' && github.event_name	== 'push'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - run: echo "Estou implantando na dev"
    - name: Check sfdx version
      run: sf version
    - name: Print environment variable
      run: echo "${{ vars.ENVIROMENT_NAME }}"
    - name: authentication github
      uses: actions/checkout@v2
    - name: Fetch dev branch
      run: git fetch origin dev
    - name: run python script
      run: python3 verify_delta_changes.py dev homolog

  deploymentHomolog:
    if: github.ref_name == 'homolog' && github.event_name	== 'push'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - run: echo  Estou implantando na homolog
    - run: sfdx version

  deploymentMain:
    if: github.ref_name == 'main' && github.event_name == 'push'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - run: "Estou rodando na main"
    - run: sfdx version
