name: Salesforce CI/CD pipeline

on:
  pull_request:
    branches: ["dev", "homolog", "main"]
  push: 
    branches: ["dev", "homolog", "main"]
  
jobs:

  validationDev:
    if: github.base_ref == 'dev'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full

    steps:
      - run: echo "Validating in Development environment"
    
      - name: authentication Github
        uses: actions/checkout@v2
      
      - name: Add safe.directory exception
        run: git config --global --add safe.directory /__w/CICD_Actions/CICD_Actions

      - name: Git fetch
        run: git fetch --all

      - name: Verifying changes
        run: echo "CHANGED_FILES=$(python3 verify_delta_changes.py origin/${{ github.head_ref }} origin/${{ github.base_ref }})" >> $GITHUB_ENV

      - name: Show variable value
        run: echo $CHANGED_FILES

      - name: Deploy to Development environment using SFDX
        if: ${{ env.CHANGED_FILES != '' }}
        run: |
          sf project convert source -r force-app -p $CHANGED_FILES -d converted/main
          sf login functions jwt --username ${{ vars.USERNAME }} --keyfile ${{ secrets.PRIVATE_KEY }} --clientid ${{ secrets.CLIENT_ID }} --instanceurl ${{ vars.INSTANCE_URL }}
          sf project deploy validate --metadata-dir converted/main -l RunLocalTests
    
  validationHomolog:
    if: github.base_ref == 'homolog'
    environment: Homologation
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full

    steps:
    - run: echo  Estou rodando na homolog
    - run: sfdx version
    
  validationMain:
    if: github.base_ref == 'main'
    environment: Production
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full

    steps:
    - run: echo  Estou rodando na main
    - run: sfdx version
    
  deploymentDev:
    if: github.ref_name == 'dev' && github.event_name	== 'push'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - run: echo "Deploying to Development environment"

    - name: authentication Github
      uses: actions/checkout@v2

    - name: Add safe.directory exception
      run: git config --global --add safe.directory /__w/CICD_Actions/CICD_Actions

    - name: Git fetch
      run: git fetch --all

    - name: Nome das branchs
      run: |
       echo "Branch de origem ${{ github.ref }}"
       echo "Branch de destino ${{ github.base_ref }}"


    - name: Verifying changes
      run: echo "CHANGED_FILES=$(python3 verify_delta_changes.py ${{ github.ref }} ${{ github.base_ref }})" >> $GITHUB_ENV

    - name: Show variable value
      run: echo $CHANGED_FILES
    
    - name: Deploy to Development environment using SFDX
      if: ${{ env.CHANGED_FILES != '' }}
      run: |
        sf project convert source -r force-app -p $CHANGED_FILES -d converted/main
        sf login functions jwt --username ${{ vars.USERNAME }} --keyfile ${{ secrets.PRIVATE_KEY }} --clientid ${{ secrets.CLIENT_ID }} --instanceurl ${{ vars.INSTANCE_URL }}
        sf project deploy --metadata-dir converted/main -l RunLocalTests

  deploymentHomolog:
    if: github.ref_name == 'homolog' && github.event_name	== 'push'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - run: echo  Estou implantando na homolog
    - run: sfdx version

  deploymentMain:
    if: github.ref_name == 'main' && github.event_name == 'push'
    environment: Development
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
    
    steps:
    - run: "Estou rodando na main"
    - run: sfdx version
