name: Salesforce validation

on:
  pull_request:
    branches: ["dev", "homolog", "main"]
    
jobs:
  validationDev:
    if: github.base_ref == 'dev'
    runs-on: ubuntu-latest
    
    steps:
    - run: echo  Estou rodando na dev
    
  validationHomolog:
    if: github.base_ref == 'homolog'
    runs-on: ubuntu-latest
    
    steps:
    - run: echo  Estou rodando na homolog
    
  validationMain:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    
    steps:
    - run: echo  Estou rodando na main
    
    
    
